name: Add Issue to Board

on:
  issues:
    types: [opened]

permissions:
  issues: write
  repository-projects: write

jobs:
  add:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: Tweets
          column: Backlog
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          action: add
