name: Tweet

on:
  project_card:
    types: [moved]

permissions:
  issues: write
  repository-projects: write

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: Parse Issue
        uses: MichaelKohler/parse@feature/validation
        id: parse
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Tweet
        uses: MichaelKohler/tweet@feature/validation
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          cardContent: ${{ steps.parse.outputs.cardContent }}
          doneColumn: Tweeted
          twitterApiKey: ${{ secrets.TWITTER_CONSUMER_KEY }}
          twitterApiSecret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          twitterAccessToken: ${{ secrets.TWITTER_ACCESS_TOKEN_KEY }}
          twitterAccessSecret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
