name: Tweet

on:
  project_card:
    types: [moved]

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: Parse Issue
        uses: content-queue/parse@main
        id: parse
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          dateFormat: "YMDHm"
      - name: Tweet
        uses: content-queue/tweet@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          cardContent: ${{ steps.parse.outputs.cardContent }}
          twitterConsumerKey: ${{ secrets.TWITTER_CONSUMER_KEY }}
          twitterConsumerSecret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          twitterAccessTokenKey: ${{ secrets.TWITTER_ACCESS_TOKEN_KEY }}
          twitterAccessTokenSecret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
