name: Tweet

on:
  project_card:
    types: [moved]

permissions:
  issues: write

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: Parse Issue
        uses: MichaelKohler/parse@fixes
        id: parse
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Tweet
        uses: MichaelKohler/tweet@fixes
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          cardContent: ${{ steps.parse.outputs.cardContent }}
          twitterConsumerKey: ${{ secrets.TWITTER_CONSUMER_KEY }}
          twitterConsumerSecret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          twitterAccessTokenKey: ${{ secrets.TWITTER_ACCESS_TOKEN_KEY }}
          twitterAccessTokenSecret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      - name: Discard closed issues from board
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          project: Tweets
